service:
  name: mailejoe

plugins:
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ${env:REGION}
  memorySize: 256
  timeout: 120
  logRetentionInDays: 90

package:
  individually: true
  exclude:
    - node_modules/aws-sdk*

functions:
  migrate:
    handler: migrate.handler
    environment:
      SECRET_ID: /${env:STAGE}/credentials
    package:
      include:
        - ../.compiled-migrations/**
    role: LambdaMigrationRole
    vpc:
      securityGroupIds:
        - ${env:SG}
      subnetIds:
        - ${env:SUBNET1}
        - ${env:SUBNET2}

resources:
  Resources:
    LambdaMigrationRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /lambda/
        RoleName: LambdaMigrationRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaMigrationPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DetachNetworkInterface
                    - ec2:DeleteNetworkInterface
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - secretsmanager:ListSecrets
                    - secretsmanager:GetSecretValue
                  Resource: '*'
